allowBuilds:
  esbuild: true

blockExoticSubdeps: true
minimumReleaseAge: 4320
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
trustPolicy: no-downgrade

overrides:
  "esbuild@>=0.27.3 <0.28.1": "^0.28.1"
  "postcss@<=8.5.17": "^8.5.18"
  "postcss>nanoid": "3.3.18"
  "read-yaml-file>js-yaml": "3.15.1"
  "@changesets/parse>js-yaml": "4.3.1"
